version: '3.8'

services:
  app:
    image: test-docker
    ports:
      - "80:80"
    environment:
      SPRING_MYSQL_URL: ${SPRING_MYSQL_URL}
      SPRING_MYSQL_USERNAME: ${SPRING_MYSQL_USERNAME}
      SPRING_MYSQL_PASSWORD: ${SPRING_MYSQL_PASSWORD}
      SPRING_MONGODB_URI: ${SPRING_MONGODB_URI}
      SPRING_GOOGLE_CLIENT_ID: ${SPRING_GOOGLE_CLIENT_ID}
      SPRING_GOOGLE_CLIENT_SECRET: ${SPRING_GOOGLE_CLIENT_SECRET}
      SPRING_GOOGLE_MAIL_USERNAME: ${SPRING_GOOGLE_MAIL_USERNAME}
      SPRING_GOOGLE_MAIL_PASSWORD: ${SPRING_GOOGLE_MAIL_PASSWORD}
      SPRING_JWT_SECRET: ${SPRING_JWT_SECRET}
      SPRING_CORS_ALLOWED_ORIGINS: ${SPRING_CORS_ALLOWED_ORIGINS}
      SPRING_OAUTH2_PASSWORD: ${SPRING_OAUTH2_PASSWORD}
      SPRING_OAUTH2_REDIRECT_URI: ${SPRING_OAUTH2_REDIRECT_URI}
      SPRING_S3_BUCKET: ${SPRING_S3_BUCKET}
      SPRING_S3_REGION: ${SPRING_S3_REGION}
      SPRING_S3_ACCESS_KEY: ${SPRING_S3_ACCESS_KEY}
      SPRING_S3_SECRET_KEY: ${SPRING_S3_SECRET_KEY}
      SPRING_GITHUB_TOKEN: ${SPRING_GITHUB_TOKEN}

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"