spring:
  application.name: CrewDock

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}

  mail:
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}

jwt:
  secret: ${JWT_SECRET}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

app:
  oauth2:
    password: ${APP_OAUTH2_PASSWORD}
    auth-redirect-uri: ${APP_OAUTH2_AUTH_REDIRECT_URI}

cloud:
  aws:
    s3:
      bucket: ${CLOUD_AWS_S3_BUCKET}
    region.static: ${CLOUD_AWS_REGION_STATIC}
    credentials:
      accessKey: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      secretKey: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}

github:
  token: ${GITHUB_TOKEN}