name: Build and Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build -x test

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |  
          docker build -f ./Dockerfile -t wns0901/docker-test:latest .
          docker push wns0901/docker-test:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: ec2 서버에 docker-compose.yml 전송
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker-compose down || true
            export SPRING_MYSQL_URL=${{ secrets.SPRING_MYSQL_URL }}
            export SPRING_MYSQL_USERNAME=${{ secrets.SPRING_MYSQL_USERNAME }}
            export SPRING_MYSQL_PASSWORD=${{ secrets.SPRING_MYSQL_PASSWORD }}
            export SPRING_MONGODB_URI=${{ secrets.SPRING_MONGODB_URI }}
            export SPRING_GOOGLE_CLIENT_ID=${{ secrets.SPRING_GOOGLE_CLIENT_ID }}
            export SPRING_GOOGLE_CLIENT_SECRET=${{ secrets.SPRING_GOOGLE_CLIENT_SECRET }}
            export SPRING_GOOGLE_MAIL_USERNAME=${{ secrets.SPRING_GOOGLE_MAIL_USERNAME }}
            export SPRING_GOOGLE_MAIL_PASSWORD=${{ secrets.SPRING_GOOGLE_MAIL_PASSWORD }}
            export SPRING_JWT_SECRET=${{ secrets.SPRING_JWT_SECRET }}
            export SPRING_CORS_ALLOWED_ORIGINS=${{ secrets.SPRING_CORS_ALLOWED_ORIGINS }}
            export SPRING_OAUTH2_PASSWORD=${{ secrets.SPRING_OAUTH2_PASSWORD }}
            export SPRING_OAUTH2_REDIRECT_URI=${{ secrets.SPRING_OAUTH2_REDIRECT_URI }}
            export SPRING_S3_BUCKET=${{ secrets.SPRING_S3_BUCKET }}
            export SPRING_S3_REGION=${{ secrets.SPRING_S3_REGION }}
            export SPRING_S3_ACCESS_KEY=${{ secrets.SPRING_S3_ACCESS_KEY }}
            export SPRING_S3_SECRET_KEY=${{ secrets.SPRING_S3_SECRET_KEY }}
            export SPRING_GITHUB_TOKEN=${{ secrets.SPRING_GITHUB_TOKEN }}
            docker-compose up -d
