name: Build and Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build -x test

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t ${{secrets.DOCKER_USERNAME}}/your-app-name .
          docker push ${{secrets.DOCKER_USERNAME}}/your-app-name

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker stop your-app-name || true
            docker rm your-app-name || true
            docker pull ${{secrets.DOCKER_USERNAME}}/your-app-name
            docker run -d -p 80:80 \
              -e SPRING_MYSQL_URL=${{ secrets.SPRING_MYSQL_URL }} \
              -e SPRING_MYSQL_USERNAME=${{ secrets.SPRING_MYSQL_USERNAME }} \
              -e SPRING_MYSQL_PASSWORD=${{ secrets.SPRING_MYSQL_PASSWORD }} \
              -e SPRING_MONGODB_URI=${{ secrets.SPRING_MONGODB_URI }} \
              -e SPRING_GOOGLE_CLIENT_ID=${{ secrets.SPRING_GOOGLE_CLIENT_ID }} \
              -e SPRING_GOOGLE_CLIENT_SECRET=${{ secrets.SPRING_GOOGLE_CLIENT_SECRET }} \
              -e SPRING_GOOGLE_MAIL_USERNAME=${{ secrets.SPRING_GOOGLE_MAIL_USERNAME }} \
              -e SPRING_GOOGLE_MAIL_PASSWORD=${{ secrets.SPRING_GOOGLE_MAIL_PASSWORD }} \
              -e SPRING_JWT_SECRET=${{ secrets.SPRING_JWT_SECRET }} \
              -e SPRING_CORS_ALLOWED_ORIGINS=${{ secrets.SPRING_CORS_ALLOWED_ORIGINS }} \
              -e SPRING_OAUTH2_PASSWORD=${{ secrets.SPRING_OAUTH2_PASSWORD }} \
              -e SPRING_OAUTH2_REDIRECT_URI=${{ secrets.SPRING_OAUTH2_REDIRECT_URI }} \
              -e SPRING_S3_BUCKET=${{ secrets.SPRING_S3_BUCKET }} \
              -e SPRING_S3_REGION=${{ secrets.SPRING_S3_REGION }} \
              -e SPRING_S3_ACCESS_KEY=${{ secrets.SPRING_S3_ACCESS_KEY }} \
              -e SPRING_S3_SECRET_KEY=${{ secrets.SPRING_S3_SECRET_KEY }} \
              -e SPRING_GITHUB_TOKEN=${{ secrets.SPRING_GITHUB_TOKEN }} \
              ${{secrets.DOCKER_USERNAME}}/your-app-name